env:
  node: true
extends: airbnb-base
parserOptions:
  ecmaVersion: 2018
rules:
  no-console: 0
  arrow-parens: 0
  consistent-return: 0
  implicit-arrow-linebreak: 0
  # as long as semicolons are enforced, this rule is unnecessary
  no-plusplus: 0
  no-continue: 0
  object-curly-newline: 0
